all:
	# g++ -O3 -o akmc -std=c++11 -I /u/samsstud/local/include -I /u/samsstud/local/cxxopts/include/ -I /u/samsstud/local/include/EIGEN main.cpp tree.cpp
	python setup.py build_ext --inplace

clean:
	rm *.so

